import { ethers } from "hardhat";
import { poseidonContract } from "circomlibjs";
import type { Signer } from "ethers";

/// Deploy the EVM Poseidon(2) hasher generated by circomlibjs — it matches the circuit.
export async function deployPoseidonHasher(signer: Signer) {
  const abi = poseidonContract.generateABI(2);
  const bytecode = poseidonContract.createCode(2);
  const factory = new ethers.ContractFactory(abi as any, bytecode, signer);
  const hasher = await factory.deploy();
  await hasher.waitForDeployment();
  return hasher;
}
